New Build System
PaulHatcherR3/corda pull request #12
Opened 2020-09-23 17:21 UTC by benmcmahon100

New main PR for the new build system

2020-09-28 16:19 UTC, chrisr3 reviewed
That was fun. For the record, while I'm definitely not a fan of Groovy, it did _at least_ have the saving grace of not requiring all of the extra nonsense that the Kotlin DSL has, for example:
```kotlin
${properties["thingy"]}
```
vs just
```groovy
$thingy
```

2020-09-28 16:19 UTC, chrisr3 commented on core-deterministic/build.gradle.kts
> +}
Don't bother, just remove from `settings.gradle`.

2020-09-28 16:19 UTC, chrisr3 commented on build.gradle.kts
> +    tasks.withType<Jar>().forEach { task ->
You probably want to use
```kotlin
tasks.withType<Jar>.configureEach { task ->
```
here, see [Gradle Task Configuration Avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html).

2020-09-28 16:19 UTC, chrisr3 commented on build.gradle.kts
> +            attributes("Automatic-Module-Name" to "net.corda.${task.project.name.replace('-', '.')}")
I have always suspected that we are generating incorrect `Automatic-Module-Name` values here; I think they're meant to match the name of the jar's "root package".

2020-09-28 16:19 UTC, chrisr3 commented on build.gradle.kts
> +        withType<Test> {
Why is `withType<JavaCompile>` using `forEach`, while `withType<Test>` isn't? And shouldn't they both be using `configureEach` anyway?

2020-09-28 16:19 UTC, chrisr3 commented on build.gradle.kts
> +            compileKotlin.kotlinOptions.freeCompilerArgs += "-Xjvm-default=compatibility"
Seeing as we're not concerned with ABI compatibility with previous versions of Corda, now is an excellent time to change this to
```kotlin
"-Xjvm-default=enable"
```

2020-09-28 16:19 UTC, chrisr3 commented on build.gradle.kts
> +        implementation(kotlin("stdlib"))
Why doesn't this dependency include `${properties["kotlinVersion"]}`, like all of the other Kotlin dependencies?

2020-09-28 16:19 UTC, chrisr3 commented on build.gradle.kts
> +    id("com.jfrog.artifactory") version "4.17.2"
You can migrate all of these plugin version numbers into a `pluginManagement` block in `settings.gradle`, where you can also use the `${properties[blah]}` expansions.

2020-09-28 16:19 UTC, chrisr3 commented on build.gradle.kts
> +    javaTestCompiler.options.compilerArgs.addAll(listOf("--add-exports",
Good idea. Something like:
```
tasks.withType(JavaCompile).matching { it.name == 'compileTestJava' }.configureEach {
    ...
}
```
except obviously in Kotlin DSL.

2020-09-28 17:10 UTC, chrisr3 reviewed
Hmm, I see you have discarded all of the `capsule` modules. But maybe no-one will notice because you have also stripped out the _entire_ publication infrastructure that configured the `maven-publish`, `com.jfrog.artifactory` and `com.jfrog.bintray` plugins.

2020-09-28 17:10 UTC, chrisr3 commented on client/rpc/build.gradle.kts
> +dependencies {
Suspicious lack of a `plugins` block here. Even if you intend to re-invent the publication wheel, you will still need to include _at least_ the Artifactory plugin here.

2020-09-28 18:58 UTC, chrisr3 commented
FYI, the Kotlin DSL became "production-ready" back in Gradle 5.0 with [this announcement](https://docs.gradle.org/5.0/release-notes.html):
> First and foremost, Gradle Kotlin DSL is now production-ready with it's 1.0 release! Authoring your build logic using Kotlin provides significant additional editing assistance in IDEs, including: improved completion, error highlighting, and refactoring tools. Please read our Gradle Kotlin DSL Primer and follow our migrating build logic from Groovy to Kotlin guide if you're interested. **If you prefer the flexibility and dynamic features of Groovy, that's totally okay — the Groovy DSL will not be deprecated.**

2020-09-28 20:01 UTC, chrisr3 commented on build.gradle.kts
> +        testRuntimeOnly("org.junit.vintage:junit-vintage-engine:${properties["junitVintageVersion"]}")
I object on general principle to having _both_ JUnit engines stuffed into any of my projects "from above"! I **guarantee** that I will only be using **one** of them.

And why aren't you using this opportunity to _**NUKE**_ JUnit 4 anyway?

2020-09-28 20:01 UTC, chrisr3 commented on build.gradle.kts
> +        testRuntimeOnly("org.junit.platform:junit-platform-launcher:${properties["junitPlatformVersion"]}")
The `junit-platform-launcher` is included with Gradle.

2020-09-28 20:10 UTC, chrisr3 commented
I don't think I've seen a single `api` dependency in any of the Gradle build scripts I've examined. FYI these are the dependencies that we will want to publish with Maven `compile` scope (as compared to `runtime` scope), and so we _are_ going to need some...

2020-09-28 20:39 UTC, chrisr3 commented on settings.gradle.kts
> +rootProject.name = "corda-project"
```groovy
pluginManagement {
    repositories {
        // plugin repositories go here, but you get gradlePluginPortal() automatically
    }

    plugins {
        id 'org.jetbrains.kotlin.jvm' version kotlin_version
        //  where "kotlin_version" is a property from the gradle.properties file.
        // And add the "Gradle Enterprise" plugin, which enables "build scans"
        id 'com.gradle.enterprise' version '3.4.1'
    }
}

plugins {
    // You apply the Gradle Enterprise plugin here, like this for Gradle 6.x.
    // I expect you'll find this useful when you repeat all of my "Task Configuration Avoidance" work.
    id 'com.gradle.enterprise'
}

// Well, it's Open Source anyway...
gradleEnterprise {
    buildScan {
        termsOfServiceUrl = 'https://gradle.com/terms-of-service'
        termsOfServiceAgree = 'yes'
    }
}

2020-09-30 09:59 UTC, mnesbit requested changes
Needs discussion in a wider forum

2020-09-30 09:59 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/crypto/internal/ProviderMap.kt
> -    put("Signature.${EdDSAEngine.SIGNATURE_ALGORITHM}", X509EdDSAEngine::class.java.name)
This is likely to have a horrendous impact on performance. We need to consider our options on this.

2020-09-30 09:59 UTC, mnesbit commented on build.gradle.kts
> +import org.gradle.api.tasks.testing.logging.TestLogEvent
We need to have a proper open discussion on if this is right architecture to go with kotlin DSL.

2020-10-01 07:53 UTC, driessamyn commented on core/src/main/kotlin/net/corda/core/crypto/internal/ProviderMap.kt
> -    put("Signature.${EdDSAEngine.SIGNATURE_ALGORITHM}", X509EdDSAEngine::class.java.name)
@mnesbit this is probably the wrong PR for you to review. This is our sandbox while we wait for the corda5 baseline. The PR you probably want to review is this one: https://github.com/corda/corda5/pull/1 which has all @PaulHatcherR3's changes to port Corda to Java 11 and Kotlin 1.4
Once this is merged, we'll raise a separate PR for our build scripts.

2020-10-01 08:00 UTC, driessamyn commented on core-deterministic/build.gradle.kts
> +}
As discussed previously, it's not our decision to make what will happen to the DJVM. Please take this up with @mnesbit 

We understood that there was uncertainty about how the DJVM will evolve, so did the minimum so it would compile and will revisit this once it's clear what there is to do.

2020-10-01 08:01 UTC, driessamyn commented on build.gradle.kts
> +        withType<Test> {
Thanks for the suggestions. This has been taken into account and we've made some changes that will be ready to review once the Corda5 repo is ready for us to raise that PR.

2020-10-01 08:08 UTC, driessamyn commented on client/rpc/build.gradle.kts
> +dependencies {
We haven't stripped out anything.
As I explained to you, we have tried to build up these scripts from first principles so that we gain an understanding of the tool and our build configuration. I also tried to explain that we haven't yet addressed the packaging and publishing side of things partly because of time constraints, partly because it's unclear to us what packaging is going to look like. We have no intention to reinvent the wheel, as you say, however the approach we'd like to take is to bring things back when required and when we understand how it should work.
I appreciate your input and, as I explained, we will be reliant on the few people who understand the current build system to help us out, so I hope this can be constructive.

2020-10-01 08:09 UTC, driessamyn commented on build.gradle.kts
> +        testRuntimeOnly("org.junit.vintage:junit-vintage-engine:${properties["junitVintageVersion"]}")
As I explained, we will take the opportunity to remove the junit 4 dependency and will remove the vintage runner once we're ready to do so.

2020-10-01 08:17 UTC, driessamyn commented on build.gradle.kts
> +        implementation(kotlin("stdlib"))
I understand the concern, and the latest version of this only has the test dependencies in this block, which we though may be useful to ensure consistency of at least the test libraries across all modules.

2020-10-01 08:19 UTC, driessamyn commented on build.gradle.kts
> +        testRuntimeOnly("org.junit.platform:junit-platform-launcher:${properties["junitPlatformVersion"]}")
That's been removed now.

2020-10-01 08:21 UTC, driessamyn commented on settings.gradle.kts
> +rootProject.name = "corda-project"
Just FYI, we've pushed the gradle build scan till later as we weren't comfortable publishing the build scans for Corda 5 while it's still private and un-announced.
We also plan a trial with Gradle Enterprise, hopefully later this year (pending legal approval).

2020-10-01 09:01 UTC, chrisr3 commented on build.gradle.kts
> +                freeCompilerArgs += "-Xjvm-default=compatibility"
`compatibility` -> `enable`. We won't get another opportunity to do this.

2020-10-01 09:09 UTC, chrisr3 commented on build.gradle.kts
> +        testRuntimeOnly("org.junit.vintage:junit-vintage-engine:${properties["junitVintageVersion"]}")
The `implementation` and `testImplementation` etc configurations are _created_ by the `java` plugin, which is also applied implicitly by the `java-library`, `kotlin` and certain other plugins. This is another reason why you cannot expect to be able to add dependencies via `allprojects` from the root project.

2020-10-01 09:18 UTC, chrisr3 commented on client/rpc/build.gradle.kts
> +dependencies {
> We haven't stripped out anything.

Except that you have: The original `build.gradle` applied its own plugins, but this new `build.kts.gradle` doesn't. The `plugins` sections for `finance/contracts` and `finance/workflows` both used to contain this comment:
```
    // Java Persistence API support: create no-arg constructor
    // see: http://stackoverflow.com/questions/32038177/kotlin-with-jpa-default-constructor-hell
```
which has now been lost too. At least some of these comments represented accumulated wisdom from the last few years of Corda development...

2020-10-01 10:23 UTC, chrisr3 commented on core-deterministic/build.gradle.kts
> +}
I think the minimum would have been commenting these modules out of `settings.gradle`
```
//include `core-deterministic`
//include `serialization-deterministic`
```
and then replacing their (few) usages in the rest of the project with `project(':core')` and `project(':serialization')` etc, on the basis that the original module are super-sets of the deterministic ones.

This would have allowed you to preserve the deterministic modules instead of - to be blunt - destroying them. _And you **have** destroyed them, because the logic for creating the `:core-deterministic` and `:serialization-deterministic` modules was encoded in their `build.gradle` files._

2020-10-01 11:20 UTC, driessamyn commented
PR superseded by the one in the corda5 repo.

2020-10-01 11:20 UTC, closed without merging