Add detekt task
PaulHatcherR3/corda pull request #13
Opened 2020-09-25 11:12 UTC by benmcmahon100

Add detekt for builds

2020-09-25 11:20 UTC, yift-r3 reviewed
Can we remove the TODO at line 8 in build.gradle.kts?

2020-09-25 11:24 UTC, benmcmahon100 commented
> Can we remove the TODO at line 8 in build.gradle.kts?

Done

2020-09-25 11:27 UTC, yift-r3 commented
In line 19, the detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.12.0") should probably be 1.13.0

We have two detekt blocks (line 58 and 126)

2020-09-25 11:31 UTC, benmcmahon100 commented
> In line 19, the detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.12.0") should probably be 1.13.0
> 
> We have two detekt blocks (line 58 and 126)

Good catch

2020-09-25 12:08 UTC, yift-r3 approved these changes

2020-09-25 12:29 UTC, driessamyn requested changes
This doesn't work.

2020-09-25 14:04 UTC, yift-r3 commented on build.gradle.kts
> +    id("io.gitlab.arturbosch.detekt") version "1.12.0"
Why not 13?

2020-09-25 14:04 UTC, yift-r3 commented on build.gradle.kts
> +        // Added to support junit5 tests
remove comment

2020-09-25 14:05 UTC, benmcmahon100 commented on build.gradle.kts
> +    id("io.gitlab.arturbosch.detekt") version "1.12.0"
It can't resolve a load of dependencies if I bump it to 13

2020-09-25 14:07 UTC, yift-r3 commented on build.gradle.kts
> +    id("io.gitlab.arturbosch.detekt") version "1.12.0"
:( Can you create a Jira ticket?

2020-09-25 14:09 UTC, benmcmahon100 commented on build.gradle.kts
> +    id("io.gitlab.arturbosch.detekt") version "1.12.0"
Yeah sure thing

2020-09-25 14:11 UTC, benmcmahon100 commented on build.gradle.kts
> +    id("io.gitlab.arturbosch.detekt") version "1.12.0"
https://r3-cev.atlassian.net/browse/INFRA-771

2020-09-25 15:24 UTC, yift-r3 approved these changes

2020-09-25 15:28 UTC, yift-r3 approved these changes

2020-09-25 16:19 UTC, yift-r3 approved these changes

2020-09-25 16:55 UTC, merged

2020-09-28 08:15 UTC, driessamyn commented on build.gradle.kts
> +                }
I don't think we need all 3 report types. We just need a machine readable and a human readable.
Currently, I don't think the human readable one is exposed in Jenkins.